# Generated by Django 3.2 on 2021-04-18 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeteerApp', '0002_rename_date_date_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date_entered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date entered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(max_length=500),
        ),
    ]
